# harness-service-account.yml 
# move this to azure-infra repo... 
apiVersion: v1  
kind: ServiceAccount  
metadata:  
  name: harness-service-account  
  namespace: default

apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: harness-sa-token-secret
  annotations:
    kubernetes.io/service-account.name: "harness-service-account"
    